version: '3.8'

services:
  nextjs_dev:
    container_name: nextjs_dev
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    image: nextjs_dev_image
    ports:
      - '3000:3000'
    volumes:
      - ../../:/app
