---
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: imbios/bun-node:18-slim
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "bun.lockb" }}
      - run:
          name: Test If we have a valid build or not
          command: |
            ls
            # bun install
            # bun run build
      - save_cache:
          key: dependency-cache-{{ checksum "bun.lockb" }}
          paths:
            - ./node_modules
            
  deploy:
    working_directory: ~/repo
    docker:
      - image: cimg/base:2024.02
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to the server and deploy
          command: |
            ls
            sh ./scripts/deploy.sh

               


workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          filters:
            tags:
              only: /.*/
          requires:
            - build
