---
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: imbios/bun-node:18-slim
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "bun.lockb" }}
      - run:
          name: Install Dependencies
          command: bun install
      - save_cache:
          key: dependency-cache-{{ checksum "bun.lockb" }}
          paths:
            - ./node_modules
  deploy:
    working_directory: ~/repo
    docker:
      - image: imbios/bun-node:18-slim
    steps:
      - setup_remote_docker
      - run:
          name: Deploy app to the server
          command: ./scripts/deploy.sh