version: 2.1
jobs:
  build:
    docker:
      - image: imbios/bun-node:18-slim
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "bun.lockb" }}
      - run:
          name: Test If we have a valid build or not
          command: |
            pwd
            bun install
            bun run build
      - save_cache:
          key: dependency-cache-{{ checksum "bun.lockb" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ./
          paths:
            - .env
            - .next/
            - public/
            - scripts/
  package:
    docker:
      - image: cimg/base:2024.02
    steps:
      - checkout
      - persist_to_workspace:
          root: ./
          paths:
            - docker/prod/*
  deploy:
    docker:
      - image: cimg/base:2024.02
    parameters:
      host:
        type: string
        default: $DEV_HOST
    steps:
      - attach_workspace:
          at: ./
      - run: 
          name : Docker ssh Setup
          command: |
            mkdir -p ~/.ssh
            [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

      - run:
          name: Login to the server and deploy
          command: |
              tar -czf /tmp/webapp.tar.gz .
              ls -a
              ssh << parameters.host >> 'bash -s' < ./scripts/ssh-setup.sh
              scp /tmp/webapp.tar.gz << parameters.host >>:~/webapp/
              ssh << parameters.host >> 'bash -s' < ./scripts/ssh-deploy.sh

          

               
# With package
workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^release-.*/
      - package:
          filters:
            tags:
              only: /^release-.*/
          requires:
            - build
      - deploy:
          filters:
            tags:
              only: /^release-.*/
          requires:
            - package