version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: imbios/bun-node:18-slim
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "bun install"
      - restore_cache:
          key: dependency-cache-{{ checksum "bun.lockb" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "bun.lockb" }}
          paths:
            - ./node_modules