version: '3.8'
services:
  bun_ci_next:
    image: achyutatp/bun-docker-next:2.0.4
    networks:
      - bun

    deploy:
      mode: replicated
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 50s

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - bun_ci_next
    ports:
      - '3000:80'
    networks:
      - bun

networks:
  bun: 
    driver: overlay