version: '3.8'
services:
  bun_ci_next:
    image: achyutatp/bun-docker-next:latest
    restart: always
    networks:
      - bun
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 5s


networks:
  bun: