version: '3.8'

services:
  nextjs_prod:
    container_name: lancon-webapp
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    image: lancon-webapp
    ports:
      - '3000:3000'
